# Generated by Django 5.0.7 on 2024-07-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_auditform_componentwitherror_componentwithouterror_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditform',
            name='case_error',
        ),
        migrations.AddField(
            model_name='auditform',
            name='is_there_any_error',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True),
        ),
    ]
