# Generated by Django 5.0.7 on 2024-07-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_auditform_case_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditform',
            name='case_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='componentwitherror',
            name='case_error',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='componentwitherror',
            name='case_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='componentwithouterror',
            name='case_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errorcase',
            name='error_definition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
