# Generated by Django 5.0.7 on 2024-07-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_auditform_case_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditform',
            old_name='is_there_any_error',
            new_name='caseError',
        ),
        migrations.RenameField(
            model_name='auditform',
            old_name='case_status',
            new_name='caseStatus',
        ),
        migrations.RenameField(
            model_name='componentwitherror',
            old_name='case_error',
            new_name='caseError',
        ),
        migrations.RenameField(
            model_name='componentwitherror',
            old_name='case_status',
            new_name='caseStatus',
        ),
        migrations.RenameField(
            model_name='componentwithouterror',
            old_name='case_status',
            new_name='caseStatus',
        ),
        migrations.RenameField(
            model_name='errorcase',
            old_name='error_definition',
            new_name='error_Definition',
        ),
    ]
