# Generated by Django 5.0.7 on 2024-07-26 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_rename_is_there_any_error_auditform_caseerror_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentwitherror',
            name='audit_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentsWithError', to='auth_app.auditform'),
        ),
        migrations.AlterField(
            model_name='componentwithouterror',
            name='audit_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentsWithoutError', to='auth_app.auditform'),
        ),
    ]
