# Generated by Django 5.0.7 on 2024-07-26 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_componentwitherror_audit_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentwitherror',
            name='audit_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentWithError', to='auth_app.auditform'),
        ),
    ]
