# Generated by Django 5.0.7 on 2024-07-31 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_componentwitherror_audit_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditform',
            old_name='audit',
            new_name='audit_type',
        ),
        migrations.RenameField(
            model_name='auditform',
            old_name='inp',
            new_name='barcode',
        ),
        migrations.RenameField(
            model_name='auditform',
            old_name='caseError',
            new_name='case_error',
        ),
        migrations.RenameField(
            model_name='auditform',
            old_name='caseStatus',
            new_name='case_status',
        ),
        migrations.RenameField(
            model_name='componentwitherror',
            old_name='caseError',
            new_name='audit_type',
        ),
        migrations.RenameField(
            model_name='componentwitherror',
            old_name='caseStatus',
            new_name='change_status',
        ),
        migrations.RenameField(
            model_name='componentwithouterror',
            old_name='caseStatus',
            new_name='change_status',
        ),
        migrations.RenameField(
            model_name='errorcase',
            old_name='error_Definition',
            new_name='error_definition',
        ),
        migrations.RemoveField(
            model_name='componentwitherror',
            name='audit',
        ),
        migrations.RemoveField(
            model_name='componentwitherror',
            name='inp',
        ),
        migrations.RemoveField(
            model_name='componentwithouterror',
            name='audit',
        ),
        migrations.RemoveField(
            model_name='componentwithouterror',
            name='inp',
        ),
        migrations.RemoveField(
            model_name='errorcase',
            name='audit',
        ),
        migrations.AddField(
            model_name='auditform',
            name='created_at',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='componentwitherror',
            name='check_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='componentwitherror',
            name='counter2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='componentwitherror',
            name='error_definition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='componentwitherror',
            name='files',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='componentwitherror',
            name='select_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='componentwitherror',
            name='sub_barcode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='componentwithouterror',
            name='check_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='componentwithouterror',
            name='counter3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='componentwithouterror',
            name='sub_barcode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='errorcase',
            name='counter1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='errorcase',
            name='files',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorcase',
            name='select_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='componentwitherror',
            name='audit_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentsWithError', to='auth_app.auditform'),
        ),
        migrations.AlterField(
            model_name='errorcase',
            name='final_error_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
