# Generated by Django 5.0.7 on 2024-08-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_rename_audit_auditform_audit_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='componentwitherror',
            name='files',
        ),
        migrations.RemoveField(
            model_name='errorcase',
            name='files',
        ),
        migrations.AddField(
            model_name='componentwitherror',
            name='files',
            field=models.ManyToManyField(blank=True, to='auth_app.fileattachment'),
        ),
        migrations.AddField(
            model_name='errorcase',
            name='files',
            field=models.ManyToManyField(blank=True, to='auth_app.fileattachment'),
        ),
    ]
