# Generated by Django 5.0.7 on 2024-08-02 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_fileattachment_remove_componentwitherror_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentwitherror',
            name='files',
        ),
        migrations.RemoveField(
            model_name='errorcase',
            name='files',
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='component_with_error',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_attachments', to='auth_app.componentwitherror'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='error_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_attachments', to='auth_app.errorcase'),
        ),
    ]
