# Generated by Django 5.0.7 on 2024-08-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_remove_componentwitherror_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentwitherror',
            name='audit_type',
        ),
    ]
