# Generated by Django 5.0.7 on 2024-08-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_remove_componentwitherror_audit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditform',
            name='case_error',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('incomplete', 'Incomplete')], max_length=10, null=True),
        ),
    ]
