# Generated by Django 5.0.8 on 2024-08-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_alter_auditform_case_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentwitherror',
            name='sub_barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
